# Generated by Django 5.2.3 on 2025-06-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
