# Generated by Django 5.2.3 on 2025-06-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
